config/routes.rb
Rails.application.routes.draw do
  get 'baseten_requests/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # ------------- Admin -------------
  # ------------- Admin -------------
  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'

  # get route for adding a new user.
  get 'admin/add_new_user', to: 'admin#add_new_user', as: 'new_add_user'

  # post route to submit the new user form
  post 'admin/add_new_user', to: 'admin#create', as: 'create_new_user'
  
  #  get route for editing user details
  get 'admin/edit_user/:id', to: 'admin#edit_user_info', as: 'edit_user_admin'

  # route to submit the edit user form
  patch 'admin/update_user/:id', to: 'admin#update_user', as:'update_user'

  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'delete_user'
  # ---------------------------------


  #post 'teachers/tasks', to: 'tasks#create', as: 'create_task'
  # Example route for a teacher's dashboard. Adjust according to your actual controller and action names.
  # get 'teachers/dashboard', to: 'teachers#dashboard', as: 'teachers_dashboard'

  # Example route for adding a new task. Adjust according to your actual controller and action names.
  #get 'teachers/add_new_task', to: 'teachers#add_new_task', as: 'new_add_task'

  # get 'students/dashboard', to: 'students#dashboard', as: 'students_dashboard'

  # Webhooks
  namespace :webhooks do
    resource :baseten, controller: :baseten, only: [:create]
  end
  
  resources :baseten_requests, only: [:create]

  resources :students, only: [:index] do
    # for testing level up modal (delete after development for this is finished)
    get :avatars, on: :collection
    post :update_avatar_id, on: :collection
  end

  resources :teachers do
    post :give_student_xp
  end

  resources :tasks do
    post :search, on: :collection
  end

  resources :users, only: [:show, :edit], path_names: { update: 'settings' } do
    post :search, on: :collection
  end


  resources :instruments, only: [:new, :create]


  resources :tasks do
    member do
      patch 'update_status_to_complete'
    end
  end

  resources :tasks do
    member do
      patch 'update_status_to_pending'
    end
  end

  authenticate :user do
    # Specific task show route - this is included in the resources :tasks above, so it's redundant here unless you need to restrict it to authenticated users only
    get 'tasks/:id', to: 'tasks#show', as: 'task_details'
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                :bigint           not null, primary key
#  attachment_paths  :string           default([]), is an Array
#  deadline          :datetime         not null
#  description       :text
#  name              :string           not null
#  recording_boolean :boolean          default(FALSE), not null
#  reward_xp         :integer          not null
#  status            :integer          default("todo"), not null
#  student_text      :text
#  time_set          :datetime         not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  instrument_id     :bigint           default(1), not null
#  student_id        :integer          not null
#  teacher_id        :integer          not null
#
# Indexes
#
#  index_tasks_on_instrument_id  (instrument_id)
#
# Foreign Keys
#
#  fk_rails_...  (instrument_id => instruments.id)
#

class Task < ApplicationRecord
  belongs_to :teacher, -> { where(role: 1) }, class_name: 'User'
  belongs_to :student, -> { where(role: 0) }, class_name: 'User'
  belongs_to :instrument

  has_many_attached :files
  has_many_attached :recordings
  

  enum status: { todo: 0, pending: 1, completed: 2 }

  # This validates that when a task is set, everything is filled out
  validates :student_id, :instrument_id, :name, :description, :reward_xp, :deadline, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validate :at_least_one_student

  def deadline_readable
    day = deadline.strftime('%-d')
    month = deadline.strftime('%B')
    year = deadline.strftime('%Y')

    "#{day} #{month} #{year}"
  end

  private

  def at_least_one_student
    errors.add(:student_id, "can't be blank") if student_id.blank?
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show destroy new create ]
  before_action :set_role

  authorize_resource

  # GET /tasks
  def index
    @tasks = Task.all
    @tasks = @tasks.where(teacher_id: current_user.id) if @user_is_teacher
    @tasks = @tasks.where(student_id: current_user.id) if @user_is_student
  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
  end

  # PATCH
  def update_status_to_pending
    @task = Task.find(params[:id])

    User.give_student_xp_points(current_user, @task.reward_xp / 2)
    current_user.save
    @task.update(student_text: params[:task][:student_text]) if params[:task][:student_text].present?

    # Attach audio files
    if params[:task][:recordings].present?
      @task.recordings.attach(params[:task][:recordings])
    end

    if @task.save
      @task.update(status: 'pending')
      redirect_to tasks_path, notice: 'Task status updated to pending.'
    else
      # Handle the case when saving the task fails
      render :show, alert: 'Failed to update task status.'
    end
  end

  def update_status_to_complete
    @task = Task.find(params[:id])

    User.give_student_xp_points(current_user, @task.reward_xp / 2)
    current_user.save
    

    if @task.save
      @task.update(status: 'completed')
      redirect_to tasks_path, notice: 'Task status updated to completed.'
    else
      # Handle the case when saving the task fails
      render :show, alert: 'Failed to update task status.'
    end
  end
  
  # GET /tasks/new
  def new
    @students = params[:student_ids] ? User.find(params[:student_ids]) : User.where(role: :student)
    @instruments = Instrument.all
  end

  # POST /tasks
  def create
    student_ids = params[:task].delete(:student_id).reject(&:empty?) # Remove empty elements
    @students = params[:student_ids] ? User.find(params[:student_ids]) : User.where(role: :student)
    @instruments = Instrument.all
    @tasks = []
  
    # Iterate over each student ID and create a new task
    student_ids.each do |student_id|
      current_task = Task.new(task_params)
      current_task.student_id = student_id
      current_task.teacher_id = current_user.id
      current_task.time_set = Time.current
  
      if current_task.save
        @tasks << current_task
      else
        @task = current_task
        render :new and return
      end
    end
  
    if @tasks.all?(&:persisted?)
      redirect_to teachers_path, notice: 'Tasks were successfully created.'
    end
  end

  
  # PATCH
  def create_from_tamplate
    
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to teachers_path, notice: 'Task was successfully deleted.'
  end

  # POST /tasks/search
  def search
    # Initial sort of tasks based on the user
    if @user_is_student
      @tasks = Task.where(student_id: current_user.id)
    elsif @user_is_teacher
      @tasks = Task.where(teacher_id: current_user.id)
    else
      @tasks = Task.all
    end

    # Search by intrument
    if params[:search][:instrument_id].present?
      @tasks = @tasks.where(instrument_id: params[:search][:instrument_id])
    end
      
    # Search by student or/and teacher
    if params[:search][:teacher_id].present? && params[:search][:student_id].present?
      @tasks = @tasks.where(teacher_id: params[:search][:teacher_id], student_id: params[:search][:student_id])
    elsif params[:search][:student_id].present?
      @tasks = @tasks.where(student_id: params[:search][:student_id])
    elsif params[:search][:teacher_id].present?
      @tasks = @tasks.where(teacher_id: params[:search][:teacher_id])
    end

    # Search by name
    @tasks = @tasks.where('name LIKE ?', "%#{params[:search][:name]}%") if params[:search][:name].present?
    
    authorize! :search, Task
    render :index
  end

  private

  def set_role
    @user_is_student = current_user.role == 'student'
    @user_is_teacher = current_user.role == 'teacher'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = params[:task_id] ? Task.find(params[:task_id]) : Task.new
  end

    # Only allow a list of trusted parameters through.
    
    def task_params
      params.require(:task).permit(:name, :instrument_id, :teacher_id, :description, :deadline, :recording_boolean, :reward_xp, :student_text, student_id: [], files: [], recordings: [])
      #sanitizing for XSS attacks
      #params.require(:task).permit(:name, :instrument_id, :teacher_id, :description, :deadline, :recording_boolean, :reward_xp, :student_text, student_id: [], files: []).transform_values { |v| sanitize(v) }
    end
    
end

app/views/tasks/index.html.haml
- status_class_mapping = {"completed" => "table-success", "todo" => "table-danger", "pending" => "table-warning"}

.card
  .card-header.text-center
    %h2 Tasks
    %h5 There are #{@tasks.select { |task| task.status == 'todo' }.size} tasks to do
  
  = simple_form_for :search, url: search_tasks_path, method: :post do |f|
    .row.p-3
      .col-md-4
        = f.input :name
      .col-md-4
        - if @user_is_student
          = f.input :teacher_id, as: :select, collection: @tasks.map(&:teacher).uniq.map { |teacher| [teacher.full_name, teacher.id] }
        - elsif @user_is_teacher
          = f.input :student_id, as: :select, collection: @tasks.map(&:student).uniq.map { |student| [student.full_name, student.id] }
        - else
          = f.input :teacher_id, as: :select, collection: @tasks.map(&:teacher).uniq.map { |teacher| [teacher.full_name, teacher.id] }
          = f.input :student_id, as: :select, collection: @tasks.map(&:student).uniq.map { |student| [student.full_name, student.id] }
      .col-md-2.mt-auto
        = f.submit 'Search', class: 'btn btn-outline-secondary'
        = link_to 'Reset', tasks_path, class: 'btn btn-outline-secondary'
  .table-responsive.mx-3
    %table.table
      %thead
        %tr
          %th Task
          %th Instrument
          %th Description
          %th Reward XP
          %th Deadline
          - if @user_is_student
            %th Teacher
          - elsif @user_is_teacher
            %th Student
          - else
            %th Teacher
            %th Student
          %th Status
          - if @user_is_student
            %th
          - else
            %th Template
            %th
            %th
      %tbody
        - @tasks.each do |task|
          %tr{ class: status_class_mapping[task.status.to_s] }
            %td.align-middle= task.name
            %td.align-middle= task.instrument.name
            %td.align-middle= task.description
            %td.align-middle= task.reward_xp
            %td.align-middle= task.deadline_readable
            - if @user_is_student
              %td.align-middle= task.teacher.full_name
            - elsif @user_is_teacher
              %td.align-middle= task.student.full_name
            - else 
              %td.align-middle= task.teacher.full_name
              %td.align-middle= task.student.full_name
            %td.align-middle.fs-4
              - if task.status.to_s == "completed"
                %i.bi.bi-check2-all
              - elsif task.status.to_s == "pending"
                %i.bi.bi-check2
              - else
                %i.bi.bi-clock-history
            - if @user_is_student
              %td.align-middle
                .btn-toolbar.float-end
                  - if task.status.to_s == "todo"
                    = link_to 'Do', task_details_path(task), class: 'btn btn-outline-secondary btn-sm'
                  - else
                    = link_to 'View', task_details_path(task), class: 'btn btn-outline-secondary btn-sm'
            - else
              %td.align-middle
                .btn-toolbar.float-end
                  - if task.status.to_s == "pending"
                    = link_to 'Grade', task_details_path(task), class: 'btn btn-outline-secondary btn-sm'
                .btn-toolbar.float-end
                  = link_to 'Use as template', new_task_path(task_id: task.id), class: 'btn btn-outline-secondary btn-sm'

app/views/tasks/new.html.haml
- content_for :title, 'Set Task'

.container.mt-2.mb-5
  .row.justify-content-center
    .col-sm-6.col-lg-10
      .card.card-light.border-0.rounded-4.shadow-lg.px-3
        .card-header.border-0.bg-transparent.text-center.pt-3.pb-0
          %h3 Set task
        - if @task.errors.any?
          .alert.alert-danger
            %h5 Please fill out all required fields
            -#- if @task.errors.full_messages.include?"Instrument can't be blank"

        .card-body.border-0.bg-transparent.pt-0
          = simple_form_for @task, url: tasks_path, method: :post do |f|
            .mb-3
              = f.select :student_id, @students.map { |student| [student.full_name, student.id] }, {}, { multiple: true, class: 'js-example-basic-multiple', name: 'task[student_id][]', required: true }
            = f.input :name, label: false, input_html: { placeholder: 'Task Name', required: true }, wrapper_html: { class: 'mb-3' }
            .mb-3
              - @task.instrument_id = nil
              - error_class = @task.errors.full_messages.include?("Instrument can't be blank") ? 'is-invalid' : ''
              = f.label "Select instrument", class: "form-label"
              = f.select :instrument_id, @instruments.map { |instrument| [instrument.name, instrument.id] }, {}, { class: "js-example-basic-single #{error_class}", name: 'task[instrument_id]', required: true }
            
              - if @task.errors.full_messages.include?"Instrument can't be blank"
                .div.invalid-feedback
                  Instrument can't be blank
            = f.input :description, label: false, input_html: { placeholder: 'Task Description', required: true }, label_html: { class: 'form-label' }, wrapper_html: { class: 'mb-3' }
            = f.input :reward_xp, as: :integer, label: 'Experience Points', input_html: { placeholder: '0', required: true }, label_html: { class: 'form-label' }, wrapper_html: { class: 'mb-3' }
            = f.input :deadline, label: "Deadline", as: :date, html5: true, input_html: { min: Date.today, required: true }, label_html: { class: 'form-label' }, wrapper_html: { class: 'mb-3' }
            = f.input :recording_boolean, label: "Allow Recording?", collection: [['Yes', true], ['No', false]], selected: 'Yes', label_html: { class: 'form-label' }, wrapper_html: { class: 'mb-3' }
            -# - @task.files.each do |file|
              -# = f.input :files, as: :hidden, input_html: { value: file.signed_id } # = f.input :files, as: :hidden, input_html: { multiple: true }, value: file.signed_id if file.attached?
              -# = f.input :files, as: :hidden, input_html: { multiple: true }, value: file.signed_id if file.attached?
            = f.input :files, as: :file, label: 'Attach files', wrapper_html: { class: 'mb-3' }, input_html: { class: 'form-control', multiple: true, accept: "application/pdf,image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document" }, label_html: { class: 'form-label' }
            = f.button :submit, "Submit", class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 mt-2'
            = link_to 'Cancel', teachers_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 mt-2 ms-2', data: { confirm: 'Are you sure?' }

:javascript
  $(document).ready(function() {
    $('.js-example-basic-multiple').select2({
      placeholder: 'Select Student(s)',
      width: '100%',
      allowClear: true
    });

    $('.js-example-basic-single').select2({
      placeholder: 'Select Instrument',
      width: '100%',
      allowClear: true
    });
  });

app/views/tasks/show.html.haml
.container.my-4
  .card.border-0.shadow.rounded-4
    .card-header.text-white.rounded-4.bg-primary.shadow
      %h5.mb-0= @task.name
    
    .card-body.shadow.rounded-bottom-4
      %p= "Task: " + @task.description
      %p= "Intrument: " + @task.instrument.name
      - if @task.files.attached?
        .mt-4
          %h5.mb-3 Attachments
          - @task.files.each do |file|
            .border.p-3.rounded-4.mb-3
              - if file.content_type.include?('pdf') || file.content_type.include?('text') || file.content_type.include?('word') || file.content_type.include?('document')
                %iframe.rounded-4{src: url_for(file), style: 'width:100%; height:500px;', frameborder: '0'}
              - else
                %p= link_to file.filename.to_s, url_for(file), download: true, class: 'btn btn-link'
      
      - if @task.recordings.attached?
        .mt-4
          %h5.mb-3 Recordings
          - @task.recordings.each_with_index do |recording, index|
            %p Recording #{index + 1}
            %audio.playback{controls: true}
              %source{src: url_for(recording), type: recording.content_type}
      
      - if @task.student_text
        %h5.mb-3 Student's note
        .border.p-3.rounded-4
          %p=@task.student_text

      - if @task.status == 'todo'   
        #recording-controls.mt-4
          .d-flex.flex-column.gap-3
            - 1.times do |i|
              .recording-set.border.p-3.rounded-4
                %p.d-block.font-weight-bold Recording #{i + 1}
                .p-3.text-warning-emphasis.bg-warning-subtle.border-0.border-start.border-5.border-warning-subtle.rounded-end-3.mb-3
                  %strong Beta feature:
                  Please say 'Start' to begin recording. The feature works only with the first recording
                %button.record-btn.btn.btn-success.border-0.rounded-5.shadow-lg.py-2.px-3{type: 'button', onclick: 'handleRecording(this)', "data-stimulus-controller": "voice"} Start Recording
                %button.play-recording-btn.btn.btn-secondary.border-0.rounded-5.shadow-lg.py-2.px-3.ml-2{type: 'button', disabled: true, onclick: 'playRecording(this)'} Play Recording
        %button#add-recording.btn.btn-primary.border-0.rounded-5.shadow-lg.py-2.px-3.my-3{type: 'button', onclick: 'addRecording()'}
          %i.fas.fa-plus
          Add another recording
        = simple_form_for @task, url: update_status_to_pending_task_path(@task), method: :patch, html: { id: 'task-form', multipart: true } do |f|
          = f.input :student_text, as: :text, label: false, input_html: { rows: 3, class: 'form-control rounded-4', placeholder: 'Add your comments or details here...' }
          #audio-inputs
          = f.button :submit, 'Complete Task', id: 'complete-task', class: 'btn btn-success border-0 rounded-5 shadow-lg py-2 px-3 mt-3', style: 'display: none;'
    .card-footer.text-muted.border-0.bg-transparent
      %i.fas.fa-clock
      Deadline: #{@task.deadline.strftime("%A, %d %B %Y")}
  - if @task.status == "pending" && current_user.teacher?
    = simple_form_for @task, url: update_status_to_complete_task_path(@task), method: :patch, html: { id: 'task-form', multipart: true } do |f|
      = f.button :submit, 'Accept Task', id: 'complete-task', class: 'btn btn-success border-0 rounded-5 shadow-lg py-2 px-3 mt-3'