config/routes.rb
Rails.application.routes.draw do
  get 'baseten_requests/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # ------------- Admin -------------
  # ------------- Admin -------------
  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'

  # get route for adding a new user.
  get 'admin/add_new_user', to: 'admin#add_new_user', as: 'new_add_user'

  # post route to submit the new user form
  post 'admin/add_new_user', to: 'admin#create', as: 'create_new_user'
  
  #  get route for editing user details
  get 'admin/edit_user/:id', to: 'admin#edit_user_info', as: 'edit_user_admin'

  # route to submit the edit user form
  patch 'admin/update_user/:id', to: 'admin#update_user', as:'update_user'

  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'delete_user'
  # ---------------------------------


  #post 'teachers/tasks', to: 'tasks#create', as: 'create_task'
  # Example route for a teacher's dashboard. Adjust according to your actual controller and action names.
  # get 'teachers/dashboard', to: 'teachers#dashboard', as: 'teachers_dashboard'

  # Example route for adding a new task. Adjust according to your actual controller and action names.
  #get 'teachers/add_new_task', to: 'teachers#add_new_task', as: 'new_add_task'

  # get 'students/dashboard', to: 'students#dashboard', as: 'students_dashboard'

  # Webhooks
  namespace :webhooks do
    resource :baseten, controller: :baseten, only: [:create]
  end
  
  resources :baseten_requests, only: [:create]

  resources :students, only: [:index] do
    # for testing level up modal (delete after development for this is finished)
    get :avatars, on: :collection
    post :update_avatar_id, on: :collection
  end

  resources :teachers do
    post :give_student_xp
  end

  resources :tasks do
    post :search, on: :collection
  end

  resources :users, only: [:show, :edit], path_names: { update: 'settings' } do
    post :search, on: :collection
  end


  resources :instruments, only: [:new, :create]


  resources :tasks do
    member do
      patch 'update_status_to_complete'
    end
  end

  resources :tasks do
    member do
      patch 'update_status_to_pending'
    end
  end

  authenticate :user do
    # Specific task show route - this is included in the resources :tasks above, so it's redundant here unless you need to restrict it to authenticated users only
    get 'tasks/:id', to: 'tasks#show', as: 'task_details'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  # GET /students
  def index
    check_level_up
    @tasks = Task.where(student_id: current_user.id)
    
    authorize! :index, :students
  end

  #GET /students/avatars
  def avatars
  end

  # def give_student_xp
  #   User.give_student_xp_points(current_user, 600)
  # end

  # def show
  #   @task = Task.find(params[:id])
  # end

  def check_level_up
    # Logic to determine if the student recently leveled up
    # Set @show_level_up_modal to true if the condition is met
    @show_level_up_modal = current_user.recently_leveled_up?
  end

  def update_avatar_id
    current_user.avatar_id = params[:avatar_id]
    current_user.save
  end

  private
  def student_params
    params.permit(:avatar_id)
  end

end

app/views/students/_avatar.html.haml
/ AVATAR CARD
.col-md-5.p-4.text-white.d-flex.align-items-center
  .card.border-0.rounded-5.shadow-lg.text-center.mx-auto.mb-auto
    .my-auto.p-3
      .mb-3
        - begin
          - if current_user.avatar.attached? && !(current_user.avatar_id.nil?)
            - selected_avatar = current_user.avatar.find_by(id: current_user.avatar_id)
            = image_tag selected_avatar, class: 'p-0 rounded-circle img-fluid resize-image-dashboard', style: 'border: 4px solid #000;', data: { avatar_id: current_user.avatar_id }
          - else
            = image_pack_tag 'images/placeholder.png', alt: 'placeholder', class: 'p-0 rounded-circle img-fluid', style: 'border: 4px solid #000;', width: 300, height: 300
        - rescue
          - if current_user.avatar.attached? && current_user.avatar_id != 1
            - selected_avatar = current_user.avatar.find_by(id: current_user.avatar_id)
            = image_tag selected_avatar, class: 'p-0 rounded-circle img-fluid resize-image-dashboard', style: 'border: 4px solid #000;', data: { avatar_id: current_user.avatar_id }
          - else
            = image_pack_tag 'images/placeholder.png', alt: 'placeholder', class: 'p-0 rounded-circle img-fluid', style: 'border: 4px solid #000;', width: 300, height: 300
      .h3
        Level
        = current_user.level
      .progress.m-3
        .progress-bar{role: "progressbar", style: "width: #{current_user.get_current_level_progress}%", aria_valuenow: "#{current_user.get_current_level_progress}", aria_valuemin: "0", aria_valuemax: "100"}
      .--bs-success-text-emphasis  
        = current_user.xp_points  
        \/
        = current_user.xp_needed_for_next_level
        xp
      .btn.btn-primary.border-0.rounded-5.shadow-lg.py-2.px-3.ms-auto.my-4
        = link_to 'Change Avatar', avatars_students_path, class: 'text-light link-underline link-underline-opacity-0'

      %button#activateModal{"style" => "display: none;", "data-bs-target" => "#levelUpModal", "data-bs-toggle" => "modal", :type => "button"} Launch modal

app/views/students/_generate_avatar_modal.html.haml
- @backgrounds_list = ['Beach', 'Mountains', 'Forest', 'Underwater', 'Castle courtyard', 'City skyline', 'Space station', 'Enchanted garden', 'Volcano', 'Desert oasis']
- @weather_list = ['Sunny', 'Rainy', 'Snowy', 'Foggy', 'Thunderstorm', 'Windy', 'Misty', 'Rainbow', 'Aurora borealis']
- @characters_list = ['Ninja', 'Farmer', 'Pirate', 'Samurai', 'Astronaut', 'Mermaid', 'Wizard', 'Superhero', 'Robot']
- @expressions_list = ['Happy', 'Curious', 'Mischievous', 'Excited', 'Worried', 'Confused', 'Surprised']
- @facial_hair_list = ['No Facial Hair', 'Stubble', 'Goatee', 'Sideburns', 'Bushy beard']
- @time_periods_list = ['Jurassic Period', 'Stone Age', 'Ancient Egypt', 'Medieval', 'Victorian', 'Futuristic']
- @accessories_list = ['Top hat', 'Beanie', 'Straw Hat', 'Headphones', 'Sunglasses', 'Crown']

.modal.fade#generateAvatarModal(tabindex="-1" role="dialog" aria-labelledby="generateAvatarModalLabel" aria-hidden="true")
  .modal-dialog.modal-dialog-centered.modal-l
    .modal-content
      .modal-header.p-3
        %h5.modal-title#levelUpModalLabel Create new Avatar!
        %button.btn.btn-primary.border-0.rounded-5.shadow-lg.ms-auto.px-4.py-2(type="button" data-bs-dismiss="modal" aria-label="Close")
          Cancel

      .modal-body.h4.px-4.py-1.m-2
        .card-body.border-0.bg-transparent.pt-0
          = form_tag baseten_requests_path(student_id: current_user.id), method: :post, data: { turbo: false }, id: 'prompt-form' do
            .mb-3
              = label_tag :background, "Background", class: "form-label"
              = select_tag :background, options_for_select(@backgrounds_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :time_period, "Time Period", class: "form-label"
              = select_tag :time_period, options_for_select(@time_periods_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :weather, "Weather", class: "form-label"
              = select_tag :weather, options_for_select(@weather_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :character, "Character Type", class: "form-label"
              = select_tag :character, options_for_select(@characters_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :expression, "Expression", class: "form-label"
              = select_tag :expression, options_for_select(@expressions_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :facial_hair, "Facial Hair", class: "form-label"
              = select_tag :facial_hair, options_for_select(@facial_hair_list), class: 'js-example-basic-single form-control', required: true
            .mb-3
              = label_tag :accessory, "Accessory", class: "form-label"
              = select_tag :accessory, options_for_select(@accessories_list), class: 'js-example-basic-single form-control', required: true
            .mb-2.mt-3.btn-group{ role: "group", "aria-label": "Basic radio toggle button group" }
              %input.btn-check{ type: "radio", name: "gender", id: "btnradio-boy", autocomplete: "off", checked: true, value: "boy" }
              %label.btn.btn-outline-primary{ for: "btnradio-boy" } Boy

              %input.btn-check{ type: "radio", name: "gender", id: "btnradio-girl", autocomplete: "off", value: "girl" }
              %label.btn.btn-outline-primary{ for: "btnradio-girl" } Girl
            .text-center
              = button_tag "Generate Avatar", class: 'btn btn-primary btn-lg border-0 rounded-5 shadow-lg py-2 px-3 mt-2', data: { disable_with: "Processing...", turbo: false  }, name: nil, disabled: current_user.generate_tokens < 1
              
            .text-center.text-danger.mt-2.h5
              - if current_user.generate_tokens < 1
                Out of generate tokens

app/views/students/_plan.html.haml
/ STUDENT PLAN
.col-md-7.p-4
  .mx-auto
    -# %h2.pb-4.mb-0 Plan for #{Date.today.strftime("%b")}
    -# %h2.pb-4.mb-0 Monthly Planner
    -# - (Date.today.beginning_of_month..Date.today.end_of_month).each_slice(7).with_index do |week, index|
    -# - start_date = week.first.strftime("%-d %b")
    -# - end_date = week.last.strftime("%-d %b")
    -#   .pb-3.accordion
    -#     .accordion-item.rounded-3.border.border-0
    -#       %h3.accordion-header
    -#         %button.accordion-button.rounded-0.border-bottom{ class: 'collapsed', type: "button", data: { bs_toggle: "collapse", bs_target: "#collapse-week-#{index}", aria_expanded: 'false', aria_controls: "collapse-week-#{index}" } }
    -#           #{start_date} - #{end_date}
    -#       .accordion-collapse.collapse{ id: "collapse-week-#{index}" }
    -#         .accordion-body
    -#           - week.each do |day|
    -#             - today = day == Date.today
    -#             - day_id = day.strftime("%-d")
    -#             - day_name = day.strftime("%A %-d %B")
    -#             - tasks = @tasks.select { |task| task.deadline.strftime("%A %-d %B") == day_name }
    -#             .pb-3.accordion
    -#               .accordion-item.rounded-3
    -#                 %h3.accordion-header
    -#                   %button.accordion-button.rounded-3{ class: today ? '' : 'collapsed', type: "button", data: { bs_toggle: "collapse", bs_target: "#collapse-#{day_id}", aria_expanded: today ? 'true' : 'false', aria_controls: "collapse-#{day_id}" } }
    -#                     = day_name
    -#                 .accordion-collapse.collapse{ class: today ? 'show' : '', id: "collapse-#{day_id}", data: { bs_parent: "#collapse-week-#{index}" } }
    -#                   .accordion-body
    -#                     - if tasks.empty?
    -#                       No tasks for this day
    -#                     - else
    -#                       .table-responsive
    -#                         %table.table
    -#                           %thead
    -#                             %tr
    -#                               %th Task
    -#                               %th Instrument
    -#                               %th Reward XP
    -#                               %th Teacher
    -#                               %th Status
    -#                               %th
    -#                           %tbody
    -#                             - tasks.each do |task|
    -#                               %tr{ class: @status_class_mapping[task.status.to_s] }
    -#                                 %td.align-middle= task.name
    -#                                 %td.align-middle= task.instrument.name
    -#                                 %td.align-middle= task.reward_xp
    -#                                 %td.align-middle= task.teacher.full_name
    -#                                 %td.align-middle.fs-4
    -#                                   - if task.status.to_s == "completed"
    -#                                     %i.bi.bi-check2-all
    -#                                   - elsif task.status.to_s == "pending"
    -#                                     %i.bi.bi-check2
    -#                                   - else
    -#                                     %i.bi.bi-clock-history
    -#                                 %td.align-middle
    -#                                   .btn-toolbar.float-end
    -#                                     - if task.status.to_s == "todo"
    -#                                       = link_to 'Do', '#', class: 'btn btn-outline-secondary btn-sm'
    -#                                     - else
    -#                                       = link_to 'View', '#', class: 'btn btn-outline-secondary btn-sm'
    
    %h2.pb-4.mb-0 Monthly Planner
    %ul.nav.nav-tabs{ role: "tablist" }
      - (Date.today.beginning_of_month..Date.today.end_of_month).each_slice(7).with_index do |week, index|
        - week_id = "week-#{index}"
        - is_current_week = (Date.today >= week.first) && (Date.today <= week.last)
        %li.nav-item{ role: "presentation" }
          %button.nav-link{ class: (is_current_week ? 'active' : ''), id: "#{week_id}-tab", "data-bs-toggle" => "tab", "data-bs-target" => "##{week_id}", type: "button", role: "tab", "aria-controls" => "#{week_id}", "aria-selected" => (is_current_week ? 'true' : 'false') }
            = "#{week.first.strftime("%-d %b")} - #{week.last.strftime("%-d %b")}"

    .tab-content
      - (Date.today.beginning_of_month..Date.today.end_of_month).each_slice(7).with_index do |week, index|
        - week_id = "week-#{index}"
        - is_current_week = (Date.today >= week.first) && (Date.today <= week.last) 
        .tab-pane{ class: (is_current_week ? 'show active' : ''), id: "#{week_id}", role: "tabpanel", "aria-labelledby" => "#{week_id}-tab" }
          .pb-3.accordion
            .accordion-item.rounded-3.border.border-0
              .accordion-body
                - week.each do |day|
                  - today = day == Date.today
                  - day_id = day.strftime("%-d")
                  - day_name = day.strftime("%A %-d %B")
                  - tasks = @tasks.select { |task| task.deadline.strftime("%A %-d %B") == day_name }
                  .pb-3.accordion
                    .accordion-item.rounded-3
                      %h3.accordion-header
                        %button.accordion-button.rounded-3{ class: today ? '' : 'collapsed', type: "button", data: { bs_toggle: "collapse", bs_target: "#collapse-#{day_id}", aria_expanded: today ? 'true' : 'false', aria_controls: "collapse-#{day_id}" } }
                          = day_name
                      .accordion-collapse.collapse{ class: today ? 'show' : '', id: "collapse-#{day_id}", data: { bs_parent: "#collapse-week-#{index}" } }
                        .accordion-body
                          - if tasks.empty?
                            No tasks for this day
                          - else
                            .table-responsive
                              %table.table
                                %thead
                                  %tr
                                    %th Task
                                    %th Instrument
                                    %th Reward XP
                                    %th Teacher
                                    %th Status
                                    %th
                                %tbody
                                  - tasks.each do |task|
                                    %tr{ class: @status_class_mapping[task.status.to_s] }
                                      %td.align-middle= task.name
                                      %td.align-middle= task.instrument.name
                                      %td.align-middle= task.reward_xp
                                      %td.align-middle= task.teacher.full_name
                                      %td.align-middle.fs-4
                                        - if task.status.to_s == "completed"
                                          %i.bi.bi-check2-all
                                        - elsif task.status.to_s == "pending"
                                          %i.bi.bi-check2
                                        - else
                                          %i.bi.bi-clock-history
                                      %td.align-middle
                                        .btn-toolbar.float-end
                                          - if task.status.to_s == "todo"
                                            = link_to 'Do', task_details_path(task), class: 'btn btn-outline-secondary btn-sm'
                                          - else
                                            = link_to 'View', task_details_path(task), class: 'btn btn-outline-secondary btn-sm'

app/views/students/avatars.html.haml
.row.mx-auto
  .col-sm-3.mx-auto.justify-content-center
    .row
      - begin
        - if current_user.avatar.attached? && !(current_user.avatar_id.nil?)
          - selected_avatar = current_user.avatar.find_by(id: current_user.avatar_id)
          = image_tag selected_avatar, id: 'current_avatar', class: 'p-0 rounded-circle img-fluid bg-transparent', style: 'border: 4px solid #000;', data: { avatar_id: current_user.avatar_id }
        - else
          = image_pack_tag 'images/placeholder.png', alt: 'placeholder', id: 'current_avatar', class: 'p-0 rounded-circle img-fluid', style: 'border: 4px solid #000;', width: 300, height: 300
      - rescue
        - if current_user.avatar.attached? && current_user.avatar_id != 1
          - selected_avatar = current_user.avatar.find_by(id: current_user.avatar_id)
          = image_tag selected_avatar, id: 'current_avatar', class: 'p-0 rounded-circle img-fluid bg-transparent', style: 'border: 4px solid #000;', data: { avatar_id: current_user.avatar_id }
        - else
          = image_pack_tag 'images/placeholder.png', alt: 'placeholder', id: 'current_avatar', class: 'p-0 rounded-circle img-fluid', style: 'border: 4px solid #000;', width: 300, height: 300
    .row.mx-auto
      - if current_user.generate_tokens
        %button.btn.btn-primary.border-0.rounded-5.shadow-lg.py-2.px-3.mt-4.mb-2{ type: "button", "data-bs-toggle" => "modal", "data-bs-target" => "#generateAvatarModal" }
          Generate Avatar
        .row.justify-content-center.mx-auto
          You have 
          = current_user.generate_tokens
          generate tokens
      .h2.text-center.mt-5
        My Avatars
  .row.mx-auto
    - current_user.avatar.each_slice(4) do |avatar_row|
      .row.my-3
        - avatar_row.each do |avatar|
          .col-sm-3.text-center
            = image_tag avatar, class: 'p-0 rounded-circle img-fluid scaled-avatar-image', data: { avatar_id: avatar.id }
    
    = form_tag(update_avatar_id_students_path(current_user), method: :post, id: 'avatar-form') do
      = hidden_field_tag(:avatar_id, current_user.avatar_id)


  = render 'students/generate_avatar_modal'

:javascript
  //const avatars = document.querySelectorAll('.scaled-avatar-image');

  // Find the avatar with matching ID and apply the class
  //const currentAvatarId = document.querySelector("#current_avatar").dataset.avatarId; // Assuming you can access this value from Ruby
  //console.log(currentAvatarId)
  //const avatarElement = document.querySelector(`[data-avatar-id="${currentAvatarId}"]`);
  //const avatarElement = document.querySelector(`[data-avatar-id="${currentAvatarId}"]:not([id="current_avatar"])`);

  document.addEventListener('DOMContentLoaded', () => {
    // Find the avatar with matching ID and apply the class
    const avatars = document.querySelectorAll('.scaled-avatar-image');
    const currentAvatarId = document.querySelector("#current_avatar").dataset.avatarId; // Assuming you can access this value from Ruby
    const avatarElement = document.querySelector(`[data-avatar-id="${currentAvatarId}"]:not([id="current_avatar"])`);

    if (avatarElement) {
      // Add the "selected-avatar" class
      console.log(currentAvatarId);
      console.log(avatarElement.classList);
      avatarElement.classList.add('selected-avatar');
      console.log(avatarElement.classList);
    } else {
      console.error(`Avatar with ID ${currentAvatarId} not found.`);
    }

    avatars.forEach((avatar) => {
      if (screen.width < 576) {
        const width = avatarElement.offsetWidth; // Get the current width
        avatar.style.height = `${width}px`; // Set the height to match the width
      }

      avatar.addEventListener('click', async () => {
        const avatarId = avatar.dataset.avatarId;
        document.querySelector('#avatar_id').value = avatarId; // Update the hidden field

        // Submit the form
        await document.querySelector('#avatar-form').submit();

        // Reload the page after a short delay (e.g., 500 milliseconds)
        setTimeout(() => {
          window.location.reload();
        }, 50);
      });
    });
  });

app/views/students/index.html.haml
- @status_class_mapping = {"completed" => "table-success", "todo" => "table-danger", "pending" => "table-warning"}

.row.h-100.justify-content-center.text-center
  = render 'students/plan'
  
  = render 'students/avatar'


  - if @show_level_up_modal
    -# this is potentially the dumbest implementation of anything in this module
    -# but this is the only way that activating this modal works, I have spent
    -# HOURS trying to make this work and this is the only thing that has, so
    -# just allow it.. thanks. It's not my fault that bootstrap is having so many
    -# issues with me using modals

    :javascript
      document.addEventListener('DOMContentLoaded', (event) => {
        document.getElementById('activateModal').click();
      });
    
    - current_user.update(recently_leveled_up: false)
  

  -# The code in this block i've seperated by the two lined comments is what activates
  -# the below modal congratulating the user of leveling up when a user has leveled up.
  -# The way it works is too complicated to try understanding.
  -# Esentially you just need to know it works.
  -# ----------------------------------------------------------------------------------------------------------------------------------------


  .modal.fade#levelUpModal(tabindex="-1" role="dialog" aria-labelledby="levelUpModalLabel" aria-hidden="true")
    .modal-dialog.modal-dialog-centered.modal-xl
      .modal-content
        .modal-header.p-3
          -# %h5.modal-title#levelUpModalLabel Congratulations
          %button.btn.btn-primary.border-0.rounded-5.shadow-lg.ms-auto.px-4.py-2(type="button" data-bs-dismiss="modal" aria-label="Close")
            Close
        
        .modal-body.h1.p-5.m-2
          %p Level #{current_user.level} reached
          
        .modal-footer.d-flex.flex-column.justify-content-center
          .h3
            You have unlocked a generate token!