config/routes.rb
Rails.application.routes.draw do
  get 'baseten_requests/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # ------------- Admin -------------
  # ------------- Admin -------------
  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'

  # get route for adding a new user.
  get 'admin/add_new_user', to: 'admin#add_new_user', as: 'new_add_user'

  # post route to submit the new user form
  post 'admin/add_new_user', to: 'admin#create', as: 'create_new_user'
  
  #  get route for editing user details
  get 'admin/edit_user/:id', to: 'admin#edit_user_info', as: 'edit_user_admin'

  # route to submit the edit user form
  patch 'admin/update_user/:id', to: 'admin#update_user', as:'update_user'

  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'delete_user'
  # ---------------------------------


  #post 'teachers/tasks', to: 'tasks#create', as: 'create_task'
  # Example route for a teacher's dashboard. Adjust according to your actual controller and action names.
  # get 'teachers/dashboard', to: 'teachers#dashboard', as: 'teachers_dashboard'

  # Example route for adding a new task. Adjust according to your actual controller and action names.
  #get 'teachers/add_new_task', to: 'teachers#add_new_task', as: 'new_add_task'

  # get 'students/dashboard', to: 'students#dashboard', as: 'students_dashboard'

  # Webhooks
  namespace :webhooks do
    resource :baseten, controller: :baseten, only: [:create]
  end
  
  resources :baseten_requests, only: [:create]

  resources :students, only: [:index] do
    # for testing level up modal (delete after development for this is finished)
    get :avatars, on: :collection
    post :update_avatar_id, on: :collection
  end

  resources :teachers do
    post :give_student_xp
  end

  resources :tasks do
    post :search, on: :collection
  end

  resources :users, only: [:show, :edit], path_names: { update: 'settings' } do
    post :search, on: :collection
  end


  resources :instruments, only: [:new, :create]


  resources :tasks do
    member do
      patch 'update_status_to_complete'
    end
  end

  resources :tasks do
    member do
      patch 'update_status_to_pending'
    end
  end

  authenticate :user do
    # Specific task show route - this is included in the resources :tasks above, so it's redundant here unless you need to restrict it to authenticated users only
    get 'tasks/:id', to: 'tasks#show', as: 'task_details'
  end
end

app/views/admin/_instruments.html.haml
.card.border-0.bg-transparent
  .card-body.bg-transparent.pt-0
    .card-header.bg-transparent
      %h3.text-center.m-3 Instruments
      .table-responsive
        %table.table.table-striped.m-0
          %thead
            %tr
              %th Name
          %tbody
            - @instruments.each do |instrument|
              %tr 
                %td= instrument.name
      = paginate @instruments, param_name: 'instruments_page'
    .card-footer.d-flex.justify-content-center.bg-transparent.p-3 
      = link_to 'Add Instrument', new_instrument_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'

app/views/admin/_users.html.haml
.card.border-0.bg-transparent
  .card-body.bg-transparent.pt-0
    .card-header.bg-transparent
      %h3.text-center.m-3 Students
    .table-responsive
      %table.table.table-striped.m-0
        %thead
          %tr
            %th Name
            %th Username
            %th Email
        %tbody
          - @students.each do |student|
            %tr{id: "user_#{student.id}"}
              %td.align-middle= student.full_name
              %td
                .dropdown
                  %button.btn.btn-secondary.bg-transparent.text-secondary.dropdown-toggle{"type" => "button", "data-bs-toggle" => "dropdown", "aria-expanded" => "false"}
                    Instruments
                  %ul.dropdown-menu
                    - previous_instrument_names = []
                    - @tasks.select { |task| task.student_id == student.id }.each do |task|
                      - unless previous_instrument_names.include?(task.instrument.name)
                        %li
                          %p.dropdown-item= task.instrument.name
                        - previous_instrument_names << task.instrument.name

              %td.align-middle= student.username
              %td.align-middle= student.email
              %td.align-middle
                = link_to 'Edit', edit_user_admin_path(student.id), class: 'btn btn-sm btn-primary'
              %td.align-middle
                = link_to 'Delete', delete_user_path(student.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
    
    .card-header.bg-transparent
      %h3.text-center.m-3 Teachers
    .table-responsive
      %table.table.table-striped.m-0
        %thead
          %tr
            %th Name
            %th Username
            %th Email
        %tbody
          - @teachers.each do |teacher|
            %tr{id: "user_#{teacher.id}"}
              %td.align-middle= teacher.full_name
              %td.align-middle= teacher.username
              %td.align-middle= teacher.email
              %td.align-middle
                = link_to 'Edit', edit_user_admin_path(teacher.id), class: 'btn btn-sm btn-primary'
              %td.align-middle
                = link_to 'Delete', delete_user_path(teacher.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

  .card-footer.d-flex.justify-content-center.bg-transparent.p-3
    = link_to 'Add User', new_add_user_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'

app/views/admin/add_new_user.html.haml
-# #container
-#   %header
-#   %main
-#     .admin-new_user
-#       %h1 Add New User
-#       -# frozen_string_literal: true
-#       = simple_form_for @user, url: create_new_user_path do |f|
-#         = f.input :full_name, wrapper_html: { class: 'mb-3' }
-#         = f.input :email, wrapper_html: { class: 'mb-3' }
-#         = f.input :username, wrapper_html: { class: 'mb-3' }
-#         = f.input :password, wrapper_html: { class: 'mb-3' }
-#         = f.input :password_confirmation, wrapper_html: { class: 'mb-3' }
-#         = f.input :role, collection: [['Student', :student], ['Teacher', :teacher]], wrapper_html: { class: 'mb-3' }
-#         = f.input :old_enough_for_cooler_avatars, as: :boolean, label: 'Old enough for cooler avatars?', wrapper_html: { class: 'mb-3' }, inline_label: true

-#         %button.btn.btn-primary.border-0.rounded-5.shadow-lg.py-2.px-3{ type: 'submit' }
-#           Add User
-#         -#btn btn-sm btn-danger
-#         = link_to 'Cancel', admin_dashboard_path, class: 'btn-sm btn-danger'
-#         -# = link_to 'Cancel', admin_dashboard_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 ms-auto'
.container.mb-3
  .row.justify-content-center
    .col-sm-6.col-lg-10
      .card.card-light.border-0.rounded-4.shadow-lg.px-3
        .card-header.border-0.bg-transparent.text-center.pt-3.pb-0
          %h1 Add New User
        .card-body.border-0.bg-transparent.pt-0
          = simple_form_for @user, url: create_new_user_path do |f|
            = f.input :full_name, wrapper_html: { class: 'mb-3' }
            = f.input :email, wrapper_html: { class: 'mb-3' }
            = f.input :username, wrapper_html: { class: 'mb-3' }
            = f.input :password, wrapper_html: { class: 'mb-3' }
            = f.input :password_confirmation, wrapper_html: { class: 'mb-3' }
            = f.input :role, collection: [['Student', :student], ['Teacher', :teacher]], wrapper_html: { class: 'mb-3' }
            = f.input :old_enough_for_cooler_avatars, as: :boolean, label: 'Old enough for cooler avatars?', wrapper_html: { class: 'mb-3' }, inline_label: true
            = f.input :avatar, as: :hidden, value: @user.avatar.signed_id if @user.avatar.attached?
            = f.input :avatar, as: :file, label: 'Update avatar', wrapper_html: { class: 'mb-3' }, input_html: { class: 'form-control', accept: "image/jpeg,image/png" }, label_html: { class: 'form-label' }

            = f.button :submit, 'Add user', class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'
            = link_to 'Cancel', admin_dashboard_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 ms-auto'

app/views/admin/dashboard.html.haml
.row.justify-content-center
  .col-sm-12.col-lg-12
    %ul.nav.nav-tabs#myTab{role: "tablist"}
      %li.nav-item{role: "presentation"}
        %button.nav-link.active#users-tab{"data-bs-toggle" => "tab", "data-bs-target" => "#users-tab-pane", type: "button", role: "tab", "aria-controls" => "users-tab-pane", "aria-selected" => "true"} Users
      %li.nav-item{role: "presentation"}
        %button.nav-link#instruments-tab{"data-bs-toggle" => "tab", "data-bs-target" => "#instruments-tab-pane", type: "button", role: "tab", "aria-controls" => "instruments-tab-pane", "aria-selected" => "false"} Instruments

    .tab-content#myTabContent
      .tab-pane.fade.show.active#users-tab-pane{role: "tabpanel", "aria-labelledby" => "users-tab", tabindex: "0"}
        = render 'admin/users'
      .tab-pane.fade#instruments-tab-pane{role: "tabpanel", "aria-labelledby" => "instruments-tab", tabindex: "0"}
        = render 'admin/instruments'

app/views/admin/edit_user_info.html.haml
.container.mb-3
  .row.justify-content-center
    .col-sm-6.col-lg-10
      .card.card-light.border-0.rounded-4.shadow-lg.px-3
        .card-header.border-0.bg-transparent.text-center.pt-3.pb-0
          %h1 Edit User
        .card-body.border-0.bg-transparent.pt-0
          = simple_form_for @user, url: update_user_path(@user), method: :patch do |f|
            = f.input :full_name, wrapper_html: { class: 'mb-3' }
            = f.input :email, wrapper_html: { class: 'mb-3' }
            = f.input :username, wrapper_html: { class: 'mb-3' }
            - if @user.avatar.attached?
              .form-group.row
                .col-md-2.my-auto
                  = f.label "Current avatar"
                .col-md-10
                  = image_tag @user.avatar.variant(:thumb), class: 'p-4 rounded-circle w-25'
            = f.input :avatar, as: :hidden, value: @user.avatar.signed_id if @user.avatar.attached?
            = f.input :avatar, as: :file, label: 'Update avatar', wrapper_html: { class: 'mb-3' }, input_html: { class: 'form-control', accept: "image/jpeg,image/png" }, label_html: { class: 'form-label' }
            = f.input :role, collection: [['Teacher', :teacher], ['Student', :student]], wrapper_html: { class: 'mb-3' }

            = f.button :submit, 'Save Changes', class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'
            = link_to 'Cancel', admin_dashboard_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 ms-auto'

app/views/admin/new.html.haml
.container.mb-3
  .row.justify-content-center
    .col-sm-6.col-lg-10
      .card.card-light.border-0.rounded-4.shadow-lg.px-3
        .card-header.border-0.bg-transparent.text-center.pt-3.pb-0
          %h1 Add New Instrument
        .card-body.border-0.bg-transparent.pt-0
          = simple_form_for @instrument, url: instruments_path do |f|
            = f.input :name, wrapper_html: { class: 'mb-3' }

            = f.button :submit, 'Add instrument', class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'
            = link_to 'Cancel', admin_dashboard_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3 ms-auto'