config/routes.rb
Rails.application.routes.draw do
  get 'baseten_requests/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # ------------- Admin -------------
  # ------------- Admin -------------
  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'

  # get route for adding a new user.
  get 'admin/add_new_user', to: 'admin#add_new_user', as: 'new_add_user'

  # post route to submit the new user form
  post 'admin/add_new_user', to: 'admin#create', as: 'create_new_user'
  
  #  get route for editing user details
  get 'admin/edit_user/:id', to: 'admin#edit_user_info', as: 'edit_user_admin'

  # route to submit the edit user form
  patch 'admin/update_user/:id', to: 'admin#update_user', as:'update_user'

  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'delete_user'
  # ---------------------------------


  #post 'teachers/tasks', to: 'tasks#create', as: 'create_task'
  # Example route for a teacher's dashboard. Adjust according to your actual controller and action names.
  # get 'teachers/dashboard', to: 'teachers#dashboard', as: 'teachers_dashboard'

  # Example route for adding a new task. Adjust according to your actual controller and action names.
  #get 'teachers/add_new_task', to: 'teachers#add_new_task', as: 'new_add_task'

  # get 'students/dashboard', to: 'students#dashboard', as: 'students_dashboard'

  # Webhooks
  namespace :webhooks do
    resource :baseten, controller: :baseten, only: [:create]
  end
  
  resources :baseten_requests, only: [:create]

  resources :students, only: [:index] do
    # for testing level up modal (delete after development for this is finished)
    get :avatars, on: :collection
    post :update_avatar_id, on: :collection
  end

  resources :teachers do
    post :give_student_xp
  end

  resources :tasks do
    post :search, on: :collection
  end

  resources :users, only: [:show, :edit], path_names: { update: 'settings' } do
    post :search, on: :collection
  end


  resources :instruments, only: [:new, :create]


  resources :tasks do
    member do
      patch 'update_status_to_complete'
    end
  end

  resources :tasks do
    member do
      patch 'update_status_to_pending'
    end
  end

  authenticate :user do
    # Specific task show route - this is included in the resources :tasks above, so it's redundant here unless you need to restrict it to authenticated users only
    get 'tasks/:id', to: 'tasks#show', as: 'task_details'
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  # GET /teachers
  def index
    @students = User.joins(:tasks).where(role: :student, tasks: { teacher_id: current_user.id}).distinct
    @tasks = Task.where(teacher_id: current_user.id)

    authorize! :index, :teachers
  end

  def give_student_xp
    student = User.find(params[:xp_points_form][:student_id])
    xp_points = params[:xp_points_form][:number_of_xp_points].to_i

    if xp_points > 0 && xp_points <= 100
      User.give_student_xp_points(student, xp_points)
    end

    respond_to do |format|
      if xp_points > 0 && xp_points <= 100
        format.js { render js: "alert('#{xp_points} XP points given to #{student.full_name}');" }
      elsif xp_points <= 0
        format.js { render js: "alert('Error in giving XP points: number of xp points given cannot be less than 1');" }
      elsif xp_points > 100
        format.js { render js: "alert('Error in giving XP points: number of xp points given cannot be more than 100');" }
      # else
      #   format.js { render js: "alert('Error in giving XP points: unknown error');" }
      end
    end

  end

end

app/views/teachers/index.html.haml
- status_class_mapping = {"completed" => "table-success", "todo" => "table-danger", "pending" => "table-warning"}
.row.justify-content-center.p-3
  .pb-3
    .d-flex.justify-content-between.align-items-center
      %h1 My Students
      = link_to 'Set a Task', new_task_path, class: 'btn btn-primary border-0 rounded-5 shadow-lg py-2 px-3'

  %section
    - @students.each do |student|
      - username = student.username
      .pb-2.accordion{id: "#{username}"}
        .accordion-item.rounded-3
          %h3.accordion-header
            %button.accordion-button.rounded-3{ class: 'collapsed', type: "button", data: { bs_toggle: "collapse", bs_target: "#collapse-#{username}", aria_expanded: 'false', aria_controls: "collapse-#{username}" } }
              = student.full_name 
          .accordion-collapse.collapse{ id: "collapse-#{username}", data: { bs_parent: "#{username}" } }
            .accordion-body
              = simple_form_for :xp_points_form, url: teacher_give_student_xp_path(student.id), method: :post, remote: true, html: { class: 'xp-points-form', id: "xpPointsForm-#{student.id}" } do |f|
                .row.p-3
                  .col-md-2
                    = f.input :number_of_xp_points, input_html: { type: 'number', class: 'xpPointsInput', id: "xpPointsInput-#{student.id}" }
                  .col-md-2.mt-auto
                    = f.hidden_field :student_id, value: student.id
                    .mb-1
                      = f.submit 'Give Student XP', class: 'btn btn-outline-secondary xpPointsSubmit', id: "xpPointsSubmit-#{student.id}"
                    = link_to 'Reset', '#', class: 'btn btn-outline-secondary resetButton', id: "resetButton-#{student.id}", data: { target_form: "xpPointsForm-#{student.id}" }
              
              - if @tasks.where(student_id: student.id).empty?
                .card-body
                  %p No tasks available for this student
              - else
                .table-responsive
                  %table.table.table-hover
                    %thead.thead-light
                      %tr
                        %th Task
                        %th Instrument
                        %th Description
                        %th Reward XP
                        %th Deadline
                        %th Status
                        %th
                        %th
                    %tbody
                      - @tasks.where(student_id: student.id).each do |task|
                        %tr{ class: status_class_mapping[task.status] }
                          %td.align-middle= task.name
                          %td.align-middle= task.instrument.name
                          %td.align-middle= task.description
                          %td.align-middle= task.reward_xp
                          %td.align-middle= task.deadline.strftime("%e %b %Y")
                          %td.align-middle.fs-4
                            - if task.status.to_s == "completed"
                              %i.bi.bi-check2-all
                            - elsif task.status.to_s == "pending"
                              %i.bi.bi-check2
                            - else
                              %i.bi.bi-clock-history
                            %td.align-middle
                              .btn-toolbar.float-end
                                - if task.status.to_s == "pending"
                                  = link_to 'Grade', task_details_path(task), class: 'btn btn-outline-secondary btn-sm mr-2'
                              .btn-toolbar
                                = link_to 'Use as template', new_task_path(task_id: task.id), class: 'btn btn-outline-secondary btn-sm ml-2'
                          %td.align-middle
                            .btn-toolbar.float-end
                              = link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'

:javascript
  document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.resetButton').forEach(function(button) {
      var targetFormId = button.dataset.targetForm;
      var form = document.getElementById(targetFormId);

      button.addEventListener('click', function(e) {
        e.preventDefault();
        form.reset();
      });
    });
  });

-# document.querySelectorAll('.xp-points-form').forEach(function(form) {
-#   var studentId = form.dataset.studentId;
-#   var xpPointsInput = form.querySelector('.xpPointsInput');
-#   var xpPointsSubmit = form.querySelector('.xpPointsSubmit');

-#   form.addEventListener('submit', function(e) {
-#     e.preventDefault();
-#     xpPointsInput.value = '';
-#     xpPointsSubmit.disabled = false;
-#     //form.submit();
-#   });
-# });